#!/bin/bash
set -e

# Usage: sudo ./setup-security.sh --domain <domain> [--domain <domain> ...]
# Example: sudo ./setup-security.sh --domain api.example.com --domain member.example.com
#
# Sets up UFW firewall, nginx rate limiting, and fail2ban.
# Applies rate limiting to all specified domains.
# All settings are read from security.conf.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/security.conf"

DOMAINS=()

# Parse arguments
while [ $# -gt 0 ]; do
    case $1 in
        --help|-h)
            echo "Usage: sudo ./setup-security.sh --domain <domain> [--domain <domain> ...]"
            echo "Example: sudo ./setup-security.sh --domain api.example.com --domain member.example.com"
            echo ""
            echo "This will configure security for all specified domains."
            exit 0
            ;;
        --domain)
            shift
            DOMAINS+=("$1")
            ;;
        --domain=*)
            DOMAINS+=("${1#*=}")
            ;;
    esac
    shift
done

if [ ${#DOMAINS[@]} -eq 0 ]; then
    echo "Usage: sudo ./setup-security.sh --domain <domain> [--domain <domain> ...]"
    echo "Example: sudo ./setup-security.sh --domain api.example.com --domain member.example.com"
    echo ""
    echo "This will configure security for all specified domains."
    exit 1
fi

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run with sudo: sudo ./setup-security.sh --domain <domain> [--domain <domain> ...]"
    exit 1
fi

# Load shared config
if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: Config file not found: $CONFIG_FILE"
    exit 1
fi

source "$CONFIG_FILE"

echo "==> Setting up security measures for ${DOMAINS[*]}..."
echo "    Config: $CONFIG_FILE"
echo ""

# ============================================
# 1. UFW Firewall
# ============================================
echo "==> Configuring UFW Firewall..."

# Install UFW if not present
if ! command -v ufw &> /dev/null; then
    apt-get update
    apt-get install -y ufw
fi

# Reset UFW to default
ufw --force reset

# Default policies
ufw default $UFW_DEFAULT_INCOMING incoming
ufw default $UFW_DEFAULT_OUTGOING outgoing

# Allow configured ports
for PORT in $UFW_ALLOWED_PORTS; do
    ufw allow ${PORT}/tcp
done

# Enable UFW
ufw --force enable

echo "    UFW configured. Allowed ports: $UFW_ALLOWED_PORTS"
ufw status verbose

# ============================================
# 2. Nginx Rate Limiting
# ============================================
echo ""
echo "==> Configuring Nginx Rate Limiting..."

# Create rate limiting configuration
cat > /etc/nginx/conf.d/rate-limiting.conf << EOF
# Rate limiting zones (generated by setup-security.sh from security.conf)
limit_req_zone \$binary_remote_addr zone=api_limit:${NGINX_ZONE_SIZE} rate=${NGINX_RATE_API};
limit_req_zone \$binary_remote_addr zone=auth_limit:${NGINX_ZONE_SIZE} rate=${NGINX_RATE_AUTH};
limit_req_zone \$binary_remote_addr zone=general_limit:${NGINX_ZONE_SIZE} rate=${NGINX_RATE_GENERAL};
limit_conn_zone \$binary_remote_addr zone=conn_limit:${NGINX_ZONE_SIZE};
EOF

echo "    Rate limiting configuration created at /etc/nginx/conf.d/rate-limiting.conf"

# Function to apply rate limiting to a site
apply_rate_limiting() {
    local site_domain="$1"
    local nginx_site="/etc/nginx/sites-available/$site_domain"

    if [ ! -f "$nginx_site" ]; then
        echo "    Site config not found: $nginx_site (skipping)"
        return
    fi

    # Check if rate limiting is already configured
    if grep -q "limit_req zone" "$nginx_site"; then
        echo "    Rate limiting already configured for $site_domain"
        return
    fi

    # Extract the backend port from existing nginx config
    local port
    port=$(grep -oP 'proxy_pass http://127\.0\.0\.1:\K[0-9]+' "$nginx_site" | head -1)
    if [ -z "$port" ]; then
        echo "    WARNING: Could not determine backend port from $nginx_site (skipping)"
        return
    fi

    echo "    Adding rate limiting to $site_domain (backend port: $port)..."

    # Create updated config with rate limiting
    cat > "$nginx_site" << EOF
server {
    listen 80;
    listen [::]:80;
    server_name $site_domain;

    # Allow certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Rate limiting for auth endpoints (stricter)
    location /api/v1/auth/ {
        limit_req zone=auth_limit burst=${NGINX_AUTH_BURST} nodelay;
        limit_conn conn_limit ${NGINX_AUTH_CONN_LIMIT};

        proxy_pass http://127.0.0.1:$port;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Rate limiting for API endpoints
    location /api/ {
        limit_req zone=api_limit burst=${NGINX_API_BURST} nodelay;
        limit_conn conn_limit ${NGINX_API_CONN_LIMIT};

        proxy_pass http://127.0.0.1:$port;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # General rate limiting for other requests
    location / {
        limit_req zone=general_limit burst=${NGINX_GENERAL_BURST} nodelay;
        limit_conn conn_limit ${NGINX_GENERAL_CONN_LIMIT};

        proxy_pass http://127.0.0.1:$port;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Increase max body size for file uploads
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};
}
EOF

    echo "    Rate limiting applied to $site_domain -> localhost:$port"
}

# Apply rate limiting to all specified domains
for SITE_DOMAIN in "${DOMAINS[@]}"; do
    apply_rate_limiting "$SITE_DOMAIN"
done

# Test and reload nginx if any changes were made
echo "    Testing nginx configuration..."
nginx -t && systemctl reload nginx
echo "    Nginx rate limiting applied."

# ============================================
# 3. Fail2ban
# ============================================
echo ""
echo "==> Configuring Fail2ban..."

# Install fail2ban if not present
if ! command -v fail2ban-client &> /dev/null; then
    apt-get update
    apt-get install -y fail2ban
fi

# Create fail2ban filter for nginx rate limiting
cat > /etc/fail2ban/filter.d/nginx-limit-req.conf << 'EOF'
[Definition]
failregex = limiting requests, excess:.* by zone.*client: <HOST>
ignoreregex =
EOF

# Create fail2ban filter for nginx bad requests
cat > /etc/fail2ban/filter.d/nginx-badbots.conf << 'EOF'
[Definition]
failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*" (400|403|404|405|444) .*$
ignoreregex = \.(?:css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)
EOF

# Create fail2ban filter for nginx 4xx errors (potential scanners)
cat > /etc/fail2ban/filter.d/nginx-http-auth.conf << 'EOF'
[Definition]
failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*" 401 .*$
ignoreregex =
EOF

# Create fail2ban jail configuration
cat > /etc/fail2ban/jail.d/nginx.conf << EOF
# Fail2ban jails (generated by setup-security.sh from security.conf)

# Nginx rate limit violations
[nginx-limit-req]
enabled = ${F2B_LIMIT_REQ_ENABLED}
filter = nginx-limit-req
action = iptables-multiport[name=nginx-limit-req, port="http,https"]
logpath = /var/log/nginx/error.log
findtime = ${F2B_LIMIT_REQ_FINDTIME}
bantime = ${F2B_LIMIT_REQ_BANTIME}
maxretry = ${F2B_LIMIT_REQ_MAXRETRY}

# Nginx bad bots and scanners
[nginx-badbots]
enabled = ${F2B_BADBOTS_ENABLED}
filter = nginx-badbots
action = iptables-multiport[name=nginx-badbots, port="http,https"]
logpath = /var/log/nginx/access.log
findtime = ${F2B_BADBOTS_FINDTIME}
bantime = ${F2B_BADBOTS_BANTIME}
maxretry = ${F2B_BADBOTS_MAXRETRY}

# Nginx authentication failures
[nginx-http-auth]
enabled = ${F2B_HTTP_AUTH_ENABLED}
filter = nginx-http-auth
action = iptables-multiport[name=nginx-http-auth, port="http,https"]
logpath = /var/log/nginx/access.log
findtime = ${F2B_HTTP_AUTH_FINDTIME}
bantime = ${F2B_HTTP_AUTH_BANTIME}
maxretry = ${F2B_HTTP_AUTH_MAXRETRY}

# SSH protection
[sshd]
enabled = ${F2B_SSHD_ENABLED}
port = ${F2B_SSHD_PORT}
filter = sshd
logpath = /var/log/auth.log
findtime = ${F2B_SSHD_FINDTIME}
bantime = ${F2B_SSHD_BANTIME}
maxretry = ${F2B_SSHD_MAXRETRY}
EOF

# Restart fail2ban
systemctl restart fail2ban
systemctl enable fail2ban

echo "    Fail2ban configured with nginx rules."

# ============================================
# 4. Block Direct IP Access
# ============================================
echo ""
echo "==> Verifying direct IP access is blocked..."

if [ "$BLOCK_DIRECT_IP" = "true" ]; then
    if [ -f /etc/nginx/sites-available/default ]; then
        if grep -q "return 444" /etc/nginx/sites-available/default; then
            echo "    Direct IP access is blocked (returns 444)."
        else
            echo "    WARNING: Default server block exists but may not block IP access."
            echo "    Run setup-nginx.sh to configure properly."
        fi
    else
        echo "    WARNING: Default server block not found."
        echo "    Direct IP access may be possible. Run setup-nginx.sh first."
    fi
fi

# ============================================
# Summary
# ============================================
echo ""
echo "=========================================="
echo "Security Setup Complete!"
echo "=========================================="
echo ""
echo "Domains: ${DOMAINS[*]}"
echo "Config: $CONFIG_FILE"
echo ""
echo "1. UFW Firewall:"
echo "   - Allowed ports: $UFW_ALLOWED_PORTS"
echo "   - Database port NOT exposed externally"
echo ""
echo "2. Nginx Rate Limiting:"
echo "   - Auth endpoints: $NGINX_RATE_AUTH (burst=$NGINX_AUTH_BURST)"
echo "   - API endpoints: $NGINX_RATE_API (burst=$NGINX_API_BURST)"
echo "   - General: $NGINX_RATE_GENERAL (burst=$NGINX_GENERAL_BURST)"
echo "   - Applied to: ${DOMAINS[*]}"
echo ""
echo "3. Fail2ban:"
echo "   - Rate limit violations: bantime=${F2B_LIMIT_REQ_BANTIME}s, maxretry=${F2B_LIMIT_REQ_MAXRETRY}"
echo "   - Bad bots: bantime=${F2B_BADBOTS_BANTIME}s, maxretry=${F2B_BADBOTS_MAXRETRY}"
echo "   - Auth failures: bantime=${F2B_HTTP_AUTH_BANTIME}s, maxretry=${F2B_HTTP_AUTH_MAXRETRY}"
echo "   - SSH brute force: bantime=${F2B_SSHD_BANTIME}s, maxretry=${F2B_SSHD_MAXRETRY}"
echo ""
echo "4. Direct IP Access:"
echo "   - Blocked (returns 444 - connection closed)"
echo "   - Only requests via domain name are accepted"
echo ""
echo "Run audit-security.sh to verify: sudo ./audit-security.sh --domain <domain>"
echo ""
echo "Useful commands:"
echo "  ufw status                    - Check firewall status"
echo "  fail2ban-client status        - Check fail2ban status"
echo "  fail2ban-client status nginx-limit-req  - Check specific jail"
echo "  fail2ban-client unban <IP>    - Unban an IP"
echo ""
